packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/common@12.0.4'
  - '@nestjs/core@12.0.4'
  - '@nestjs/platform-fastify@12.0.4'
  - '@nestjs/testing@12.0.4'
  - '@typescript-eslint/eslint-plugin@8.70.1'
  - '@typescript-eslint/parser@8.70.1'
  - '@typescript-eslint/project-service@8.70.1'
  - '@typescript-eslint/scope-manager@8.70.1'
  - '@typescript-eslint/tsconfig-utils@8.70.1'
  - '@typescript-eslint/type-utils@8.70.1'
  - '@typescript-eslint/types@8.70.1'
  - '@typescript-eslint/typescript-estree@8.70.1'
  - '@typescript-eslint/utils@8.70.1'
  - '@typescript-eslint/visitor-keys@8.70.1'
  - typescript-eslint@8.70.1
